apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medea-stage
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: medea
  source:
    repoURL: 'git@github.com:confinale/medea-config.git'
    path: overlays/stage
    targetRevision: v0.0.6
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: medea-stage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
